# Generated by Django 3.0.6 on 2020-06-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventMangerAPI', '0003_auto_20200619_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtags',
            name='tagId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='eventTag', to='EventMangerAPI.Skill'),
        ),
    ]
