# Generated by Django 3.0.6 on 2020-07-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventMangerAPI', '0005_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPushSent',
            field=models.BooleanField(default=False),
        ),
    ]
