# Generated by Django 3.0.6 on 2020-08-03 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventMangerAPI', '0006_event_ispushsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='acceptedVendorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptedEvents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bidderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to=settings.AUTH_USER_MODEL)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventBids', to='EventMangerAPI.Event')),
            ],
        ),
    ]
