# Generated by Django 3.0.6 on 2020-08-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventMangerAPI', '0008_auto_20200803_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbid',
            old_name='bidder',
            new_name='bidderId',
        ),
        migrations.RenameField(
            model_name='eventbid',
            old_name='event',
            new_name='eventId',
        ),
    ]
