# Generated by Django 3.0.6 on 2020-08-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventMangerAPI', '0009_auto_20200803_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbid',
            old_name='bidderId',
            new_name='bidder',
        ),
    ]
