# Generated by Django 3.0.6 on 2020-08-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventMangerAPI', '0010_auto_20200803_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbid',
            name='isPushSent',
            field=models.BooleanField(default=False),
        ),
    ]
